bashrc_call_epatch_user() {
	[ -d ${S} ] && cd "${S}"

	# If eapply_user has been executed, do not execute epatch_user again
	[ -f "${T}/.portage_user_patches_applied" ] && return 0

	# Execute epatch_user
	if type epatch_user > /dev/null 2>&1 \
			&& type epatch > /dev/null 2>&1; then
		epatch_user
	else
		. ${ROOT}etc/portage/env/epatch_user.sh
		epatch_user
		# To avoid issues when writing an ebuild
		unset epatch
		unset epatch_user
	fi

	# Prevent eapply_user from being executed
	>> "${T}/.portage_user_patches_applied"
}

post_src_unpack() {
	[ -z "$LATE_EPATCH_USER" ] && bashrc_call_epatch_user
}

post_src_prepare() {
	[ -n "$LATE_EPATCH_USER" ] && bashrc_call_epatch_user
}
